"""Regenerate published contracts from code: contracts/tool-catalog.json and contracts/openapi.json.

Review the diff: a change here changes what Gemini (tool catalog) or the browser (API) can rely on.
Usage: python scripts/export_contracts.py [--check]"""
from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
for sub in ("api", "agent", "connectors", "checks"):
    sys.path.insert(0, str(ROOT / "services" / sub))

from wizard_api.app import create_app  # noqa: E402
from wizard_api.config import load_settings  # noqa: E402
from wizard_connectors.tools import build_registry, build_services  # noqa: E402


def render() -> dict[str, str]:
    registry = build_registry(build_services())
    tools = {"notice": "Generated by scripts/export_contracts.py. Read-only tools Gemini can call; MCP servers asap, gscm, "
                       "nerp and wizard each serve their scope.", "tools": registry.describe()}
    with tempfile.TemporaryDirectory() as tmp:
        app = create_app(load_settings(env={"WIZARD_DATA_DIR": tmp}, env_file=Path(tmp) / "none.env"))
        openapi = app.openapi()
        app.state.store.db.close()
    return {"tool-catalog.json": json.dumps(tools, indent=2, ensure_ascii=False) + "\n",
            "openapi.json": json.dumps(openapi, indent=2, ensure_ascii=False) + "\n"}


def main() -> int:
    files = render()
    stale = [n for n, text in files.items() if not (ROOT / "contracts" / n).exists()
             or (ROOT / "contracts" / n).read_text(encoding="utf-8") != text]
    if "--check" in sys.argv:
        if stale:
            print("Published contracts are out of date: " + ", ".join(stale) + ". Run scripts/export_contracts.py.")
            return 1
        print("Published contracts match the code.")
        return 0
    for name, text in files.items():
        (ROOT / "contracts" / name).write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote {', '.join(files)} ({len(stale)} changed).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
