"""External content folder (WIZARD_CONTENT_DIR): validation rules and loading real catalogs as navigation-only."""
from __future__ import annotations

import json
from pathlib import Path

import pytest
from fastapi.testclient import TestClient
from tests.helpers import MemoryRecorder, login, make_settings

from wizard_api.app import create_app
from wizard_api.config import ConfigError
from wizard_connectors.content import errors, validate_content
from wizard_connectors.entitlements import IdentityDirectory
from wizard_connectors.tools import ToolContext

GUIDE = """---
id: platform-asap
title: ASAP platform guide (MicroStrategy BI)
status: DRAFT_UNSIGNED
owner: TBD - ASAP IT
tags: [asap, platform, dossier, prompts]
---
**What it is.** The BI portal.
"""


def catalog(**report_overrides) -> dict:
    report = {
        "id": "asap-sell-out-weekly", "name": "Sell-out weekly by account", "folder": "asap-f-sales", "type": "report",
        "row_access": "NAVIGATION_ONLY", "file": None, "description": "Weekly sell-out units by account and model.",
        "grain": ["account", "week"], "as_of": None, "refresh": "Weekly",
        "dimensions": [{"key": "account", "label": "Account", "type": "string"}],
        "measures": [{"key": "sell_out_units", "label": "Sell-out units", "type": "integer", "unit": "units", "aggregation": "sum"},
                     {"key": "share_pct", "label": "Share %", "type": "percent", "unit": "%", "aggregation": "none"}],
        "attributes": [], "prompts": [{"key": "week", "label": "Week", "multi": True}],
        "caveats": ["DRAFT: generated by Gemini from inbox/asap/report-list.pdf; owner review required."],
        "sensitivity": "internal",
    }
    report.update(report_overrides)
    return {"contract_version": 1,
            "system": {"id": "asap", "name": "ASAP", "description": "MicroStrategy BI", "families": ["sell_out"], "owner": "TBD",
                       "connector": {"status": "NAVIGATION_ONLY", "data_mode": "LIVE_VERIFIED", "transport": "library-rest",
                                     "live_interface": "MicroStrategy Library REST"}, "open_url_template": None},
            "folders": [{"id": "asap-f-sales", "name": "Sales", "parent": None}], "reports": [report]}


def content(root: Path, contract: dict | None = None, guide: str = GUIDE, name: str = "asap") -> Path:
    (root / "contracts" / "sources").mkdir(parents=True, exist_ok=True)
    (root / "knowledge" / "platforms").mkdir(parents=True, exist_ok=True)
    (root / "contracts" / "sources" / f"{name}.json").write_text(json.dumps(contract or catalog()), encoding="utf-8")
    (root / "knowledge" / "platforms" / "asap.md").write_text(guide, encoding="utf-8")
    return root


def messages(root: Path) -> list[str]:
    return [p.message for p in errors(validate_content(root))]


def test_a_reviewed_navigation_only_catalog_is_valid(tmp_path):
    assert messages(content(tmp_path)) == []


@pytest.mark.parametrize("override, expected", [
    ({"row_access": "ROWS"}, "needs an approved live adapter"),
    ({"file": "asap/rows.csv"}, "file must be null"),
    ({"id": "gscm-sell-out"}, "must start with 'asap-'"),
    ({"folder": "nowhere"}, "unknown folder"),
    ({"measures": [{"key": "share_pct", "label": "Share", "type": "percent", "unit": "%", "aggregation": "sum"}]}, "must not be summed"),
    ({"measures": [{"key": "spend", "label": "Spend", "type": "currency", "aggregation": "sum"}]}, "needs a unit"),
    ({"extra_field": 1}, "Extra inputs are not permitted"),
])
def test_report_rules(tmp_path, override, expected):
    assert any(expected in m for m in messages(content(tmp_path, catalog(**override)))), messages(tmp_path)


def test_system_rules(tmp_path):
    synthetic = catalog()
    synthetic["system"]["connector"]["data_mode"] = "SYNTHETIC"
    assert any("SYNTHETIC belongs" in m for m in messages(content(tmp_path / "a", synthetic)))
    verified = catalog()
    verified["system"]["connector"]["status"] = "ROWS_VERIFIED"
    assert any("not allowed for real content" in m for m in messages(content(tmp_path / "b", verified)))
    assert any("must match system id" in m for m in messages(content(tmp_path / "c", catalog(), name="bi")))


def test_secrets_front_matter_and_stray_data_are_rejected(tmp_path):
    root = content(tmp_path, guide=GUIDE + "\npassword = 'hunter22secret'\n")
    (root / "knowledge" / "metrics").mkdir()
    (root / "knowledge" / "metrics" / "share.md").write_text("no front matter here", encoding="utf-8")
    (root / "exports").mkdir()
    (root / "exports" / "rows.csv").write_text("a,b\n1,2\n", encoding="utf-8")
    found = messages(root)
    assert any("credentials" in m for m in found)
    assert any("missing front matter" in m for m in found)
    assert any("do not belong in content" in m for m in found)


def test_wizard_loads_real_content_as_navigation_only(tmp_path):
    root = content(tmp_path / "wizard-content")
    app = create_app(make_settings(tmp_path, WIZARD_CONTENT_DIR=str(root), WIZARD_AGENT_RUNTIME="code-assist"))
    with TestClient(app) as client:
        login(client, "u-ceo")
        sources = client.get("/api/v1/sources").json()["sources"]
        assert [s["id"] for s in sources] == ["asap"] and sources[0]["connector_status"] == "NAVIGATION_ONLY"
        assert client.get("/api/v1/bootstrap").json()["data_modes"] == [], "nothing readable means no data-mode claim"
        catalog_view = client.get("/api/v1/sources/asap/catalog").json()
        assert catalog_view["reports"][0]["status"] == "NAVIGATION_ONLY"
        assert "content" in client.get("/api/v1/ready").json()["checks"]
    services, registry = app.state.manager.services, app.state.registry
    identity = IdentityDirectory.load(app.state.settings.identities_file).get("u-ceo")
    ctx = ToolContext(identity=identity, run_id="r", recorder=MemoryRecorder(), services=services)
    found = registry.execute("asap_search_reports", {"query": "sell-out weekly account"}, ctx)
    assert found.ok and found.data["results"][0]["report_id"] == "asap-sell-out-weekly"
    guide = registry.execute("wizard_lookup_definitions", {"query": "ASAP platform"}, ctx)
    assert guide.data["definitions"][0]["id"] == "platform-asap"
    refused = registry.execute("asap_run_report", {"report_id": "asap-sell-out-weekly"}, ctx)
    assert refused.error_code == "navigation_only"
    assert [s.name for s in registry.list("nerp")] == [], "synthetic platforms are not mixed into real content"


def test_invalid_content_stops_start_up(tmp_path):
    root = content(tmp_path / "bad", catalog(row_access="ROWS"))
    with pytest.raises(ConfigError) as error:
        create_app(make_settings(tmp_path, WIZARD_CONTENT_DIR=str(root), WIZARD_AGENT_RUNTIME="code-assist"))
    assert "validate_content.py" in str(error.value)


def test_replay_cannot_use_real_content(tmp_path):
    with pytest.raises(ConfigError):
        make_settings(tmp_path, WIZARD_CONTENT_DIR=str(content(tmp_path / "c")))
